language: android

jdk: oraclejdk7

env:
  global:
    - GRADLE_OPTS="-XX:MaxPermSize=4g -Xmx4g"
    - ANDROID_SDKS=android-23
    - ANDROID_TARGET=android-23

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-support
    - extra-android-m2repository

# as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

before_install:
    - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
    - export JAVA_HOME=$JAVA7_HOME

script:
  - cd src
  - ./gradlew clean assemble check
  - cd ..

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
      recipients:
        - panos.sakkos@gmail.com
      on_failure: always
      on_success: never
